#ifndef PIEDPIPER_SETTINGS_h
#define PIEDPIPER_SETTINGS_h

#define SAMPLE_RATE 4096
#define WINDOW_SIZE 256

#define AUD_IN_DOWNSAMPLE_RATIO 2
#define AUD_OUT_UPSAMPLE_RATIO 8
#define SINC_FILTER_DOWNSAMPLE_ZERO_X 5
#define SINC_FILTER_UPSAMPLE_ZERO_X 5

#define PLAYBACK_FILE_LENGTH 8

#define PIN_AUD_OUT A0
#define PIN_AUD_IN A2
#define PIN_HYPNOS_5VR 6
#define PIN_HYPNOS_3VR 5
#define PIN_SD_CS 11
#define PIN_AMP_SD 9
#define PIN_RTC_ALARM 12

#define DEFAULT_DS3231_ADDR 0x68
#define DEFAULT_MCP465_ADDR 0x44
#define DEFAULT_SHT31_ADDR 0x28

#define ADC_RESOLUTION 12
#define DAC_RESOLUTION 12

#endif